### ISSUE TITLE
Countries not loading with error in console on iOS 13.3 simulator

### ISSUE THREAD

**Issue by anatoliyv** [nalexn/clean-architecture-swiftui#10]
On iOS 13.3 app is not working. Infinite loading indicator with error in console
```
2020-01-27 16:36:27.686086+0200 CountriesSwiftUI[93607:5277210] 
Task <CF46B85F-26FE-4D81-917C-338E10956D73>.<1> 
finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" 
UserInfo={NSErrorFailingURLStringKey=https://restcountries.eu/rest/v2/all, 
NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://restcountries.eu/rest/v2/all}
```

**Comment by nalexn** [comment]
Hm, just tested on iOS simulator 13.3 for iPhone, iPad, and on a real device. The list of countries / details seem to work with no issues.

I've pushed couple commits (you may want to pull), but they are unrelated to the issue you're observing.

Could you retry with other targets (Catalyst, real device)?

**Comment by anatoliyv** [comment]
@nalexn Yes you're right. There were few commits I did not pull. Latest code works fine.
