### ISSUE TITLE
Question: Dealing with auth tokens using clean architecture

### ISSUE THREAD

**Issue by andreybuksha** [nalexn/clean-architecture-swiftui#22]
How should I set auth token?
After I authenticate I need to pass auth token in headers for every request.
In your article you briefly mentioned that tokens would be stored in AppState.
But how can I access token stored in state on Repository level (since we set headers over there)

**Comment by nalexn** [comment]
You can simply inject `Store<AppState>` as an init parameter at the lowest networking level (URLSession) or at the level of Repositories. AppState is created [before](https://github.com/nalexn/clean-architecture-swiftui/blob/master/CountriesSwiftUI/System/AppEnvironment.swift#L36) all the rest of the infrastructure, so you can inject it in any system module that needs it.
