### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by NeverwinterMoon** [nalexn/clean-architecture-swiftui#26]
Hi! 

Some time ago, you've swapped your own implementation of file/in memory caching in favour of URLSessionConfiguration caching. 

The latter approach does not work that well in some cases. Say, the image was missing at some specific URL (maybe the server was down), the data is returned (for instance, it was an error page) and is cached. This data couldn't be converted to image (`UIImage(data: data)`), still, every next load invocation will have wrong cached data and won't try to check if there is a valid data present.

Maybe it makes sense to manage the same URLCache but manually using CachedURLResponse, instead of using `.returnCacheDataElseLoad`?

**Comment by nalexn** [comment]
Hey @NeverwinterMoon ,
Thanks for pointing out to this interesting edge case, I've implemented a [fix](https://github.com/nalexn/clean-architecture-swiftui/commit/37a0ec3b90abf328196ad74f18e8118a8e547b70#diff-5eb91f22ae4f2cb4db3324af3ed37b67R99).
