### ISSUE TITLE
cancel() in CancelBag

### ISSUE THREAD

**Issue by golangnext** [nalexn/clean-architecture-swiftui#28]
I noticed there's a method of `cancel` in CancelBag. When to use this method? (I can not find a case in your project)

**Comment by nalexn** [comment]
Hey @golangnext , there is a [button](https://github.com/nalexn/clean-architecture-swiftui/blob/master/CountriesSwiftUI/UI/Screens/CountryDetails.swift#L78) on the Country Details screen that allows you to cancel loading the data. That button actually triggers `cancel` on the CancelBag that keeps the running request alive.

**Comment by golangnext** [comment]
oh, yes, we don't need to explicity call cancel method.  An AnyCancellable instance automatically calls cancel() when deinitialized.
