### ISSUE TITLE
Blog Suggestion: CoreData, Clean Architecture, Combine and SwiftUI

### ISSUE THREAD

**Issue by zrfrank** [nalexn/clean-architecture-swiftui#33]
Would you, at some point, write a blog post about your methods about,
how to integrate the Core Data (with CloudKit-enabled) into Clean Architecture using Combine;
and how could we from the SwiftUI update the data source, while maintaining their synchronous.

Like, how would you bridging the Data Layer(which is `struct` based) and the Core Data(which is `class of NSManagedObject`); Will the same data be duplicated? How to manage the `Fault` for relationships of the CoreData? How to reduce the amount of work when updating a large list, do we actually rebuild the entire list or just partial of the list? etc.

I've found in your existing code some great implementations, though would love to read more about it.

Many thanks!

**Comment by nalexn** [comment]
Hey @zrfrank , I've put this in the list of the topics to write about, thank you for the proposal. I cannot give you an ETA on that though, I lack free time lately, but I'll do my best!

**Comment by zrfrank** [comment]
Thanks!
