### ISSUE TITLE
cancel bag is not needed

### ISSUE THREAD

**Issue by sisoje** [nalexn/clean-architecture-swiftui#41]
AnyCancellable is doing cancel on deinit, it called RAII pattern:
https://developer.apple.com/documentation/combine/anycancellable

```
An AnyCancellable instance automatically calls cancel() when deinitialized
```

No need to call explicit cancel() on items. CancelBag looks like its not needed. It will cleanup a lot of code

**Comment by nalexn** [comment]
You're right, calling `cancel()` is not needed, but there is just [one line](https://github.com/nalexn/clean-architecture-swiftui/blob/master/CountriesSwiftUI/Utilities/CancelBag.swift#L15) in the project where it appears.

Other than that, I would argue that removing `CancelBag` is worth it. `CancelBag` is just as convenient as `Set<AnyCancellable>`, but has a clearer purpose and strictly scoped API. More importantly, `CancelBag` is a reference type, as opposed to `Set`, which allows for more predictable memory management in certain places, like `Loadable` enum.

I'm a big fan of cleaning things up, and you're welcomed to post a code snippet for comparison, but I really cannot see how `Set<AnyCancellable>` would make the code more concise or clearer.

**Comment by sisoje** [comment]
This project is overengineered enough (in a good way) I just think CancelBag would make it clearer. Would you like me to prepare a PR with removed cancel bag?

**Comment by nalexn** [comment]
I cannot forbid you from doing this, of course! Before you do, have a look at this [additional feature](https://github.com/nalexn/clean-architecture-swiftui/blob/mvvm/CountriesSwiftUI/Utilities/CancelBag.swift#L23) of `CancelBag` in the mvvm branch.

This trick actually has a [practical application](https://github.com/nalexn/clean-architecture-swiftui/blob/mvvm/CountriesSwiftUI/UI/Screens/CountriesList/CountriesListViewModel.swift#L50).

I even have a [post](https://nalexn.github.io/cancelbag-for-combine/) on my blog about it :)

>  memory management is the same whether you use value or reference.

No.

**Comment by sisoje** [comment]
ok i see this additional feature of cancelbag... well ok for the fans "sugar sythax" this function builder may be also a good think to learn 👍

**Comment by magauran** [comment]
Hi, @nalexn! You can create the same extension for Set<AnyCancellable>

```swift
extension Set where Element == AnyCancellable {
    @_functionBuilder
    struct Builder {
        static func buildBlock(_ cancellables: AnyCancellable...) -> [AnyCancellable] {
            cancellables
        }
    }
}
```

and create convenience typealias
```swift
typealias CancelBag = Set<AnyCancellable>
```
