### ISSUE TITLE
UnitTests compile error

### ISSUE THREAD

**Issue by markych96** [nalexn/clean-architecture-swiftui#57]
can't run unit tests:

'init()' is unavailable in SystemEventsHandlerTests.swift:167:9

clean-architecture-swiftui/UnitTests/System/SystemEventsHandlerTests.swift:167:9: 'init()' is unavailable

/UIKit.UIOpenURLContext:6:12: 'init()' has been explicitly marked unavailable here

**Comment by markych96** [comment]
found some workaround about that issue, ant don't know how implement this, may be this useful

https://developer.apple.com/forums/thread/29851

**Comment by nalexn** [comment]
@markych96 thanks for reporting this! Haven't used Obj-C for 5+ years, but had to appeal to it to work around the issue. The fix is pushed.
