### ISSUE TITLE
Cannot connect to REST API

### ISSUE THREAD

**Issue by stef-t** [nalexn/clean-architecture-swiftui#67]
Hey, 

fist off thanks for this insightful repository and article!

When cloning the repository and trying to run it, the application can not connect to the REST API _restcountries.eu_. Trying to access it via a browser redirects to _countrylayer.com_. 
I'm not sure what happened with the API or if it is something that just temporarily happened to me.

Kind regards

**Comment by nalexn** [comment]
Hey @stef-t thanks for the heads up!

Sadly `restcountries.eu` is now shut down and replaced with a paid `countrylayer.com`. [Their free tier](https://countrylayer.com/pricing/) is just 100 searches a month, which means it won't be able to serve everyone interested in this sample project.
 
I'm not sure there are other free REST APIs for countries search, so the simplest solution for right now is to migrate to their new APIs with key-based access and have everyone who hit the limit register a free account and substitute the new access key in the source code. That's a bummer.

**Comment by stef-t** [comment]
That is really unfortunate to hear!

Another approach might be to load some [local json](https://github.com/mledoze/countries/blob/master/countries.json) that is already part of the app. I'm not sure if the data, provided by the json I linked, matches the data that the REST API provides though.
It might be a nice extension to showcase the flexibility of your clean architecture approach.

**Comment by nalexn** [comment]
@okiookio thank you for finding this mirror, you made my day! I've pushed the fix
