### ISSUE TITLE
How to save related CoreData objects?

### ISSUE THREAD

**Issue by riley-usagi** [nalexn/clean-architecture-swiftui#69]
Hi, @nalexn .

Could you please explain how to save (store) related objects (Parent -> Childs) to the database?

Thanks.

**Comment by nalexn** [comment]
Hey @riley-usagi , you simply insert both parent and child objects in the managed context (calling `insertNewObject` on a concrete `NSEntityDescription`) and then assign the references between the objects. Here is [an example in this repo](https://github.com/nalexn/clean-architecture-swiftui/blob/master/CountriesSwiftUI/Models/Models%2BCoreData.swift#L85), where a `Country` has 1-many relationship with `NameTranslation` (check out `xcdatamodeld` file)
