### ISSUE TITLE
Why does the '.onReceive(routingUpdate)' perform twice?

### ISSUE THREAD

**Issue by GeoffreyChen777** [nalexn/clean-architecture-swiftui#74]
Hi, thanks for your work!

I'm learning your architecture and I found that:

```
.onReceive(routingUpdate) {
            print("update")  \\ added by me.
            self.routingState = $0 }
```
the print will be performed twice. Can you explain the reason?

Please forgive me for this simple question, because I am a newbie of swift :)

**Comment by nalexn** [comment]
Hey @GeoffreyChen777 

This phenomenon is explained in the section Phantom state updates of [this article](https://nalexn.github.io/stranger-things-swiftui-state/). Let me know if you have follow up questions!
