### ISSUE TITLE
Project isn't building, Xcode 13.2

### ISSUE THREAD

**Issue by riyadshauk** [nalexn/clean-architecture-swiftui#75]
Am I doing something wrong / missing a step?
<img width="1280" alt="Screen Shot 2021-12-18 at 8 39 21 AM" src="https://user-images.githubusercontent.com/8068555/146649204-88d5082e-8ecf-4133-91e1-455ca531f09f.png">

**Comment by nalexn** [comment]
Hey, your Swift Packages are not loaded. When you open the project for the first time, Xcode loads the packages automatically, in your case the loading failed for some reason. In Xcode, try File -> Packages -> "Resolve Package Versions" and "Update to latest package versions"

**Comment by Aecasorg** [comment]
Xcode 13.2 from App Store does not work properly. You need to download Xcode 13.2 directly and it'll all work. See: https://www.macrumors.com/2021/12/14/xcode-13-2-bug/
