### ISSUE TITLE
Reseting route state

### ISSUE THREAD

**Issue by MohsenKhosravinia** [nalexn/clean-architecture-swiftui#78]
Hit @nalexn, great job on you repo.
I have a question. How and when do you reset your routing states? Currently I have a hierarchy like below:
SplashView -> AuthenticationView -> SignUpView -> HomeView
I want to log out on home view and go back (move forward) to authentication view. when I change the routing state on home view and go to authentication view, all the previous flags for navigation are true and therefore the view goes forward again and again.

**Comment by nalexn** [comment]
Hey,

> How and when do you reset your routing states?

If we're talking about a real "reset" of the state, there is [one place](https://github.com/nalexn/clean-architecture-swiftui/blob/master/CountriesSwiftUI/UI/Screens/ContentView.swift#L38) I do this to essentially restart the app after appearance settings are changed by `EnvironmentOverrides` panel (a UI/UX testing tool I built, which is also demoed as part of this project).

Normally you don't want a full reset, but toggle a few flags at once to pop back to your `AuthenticationView`. That is, there should be a flag that presented SignUpView and another one that displayed HomeView, so as soon as you toggle both off you should be good.

If this tip does not help, please do provide the code of how you're changing the routing state to pop back and the routing state structure itself.

**Comment by MohsenKhosravinia** [comment]
This is the fist view (splash)


import SwiftUI
import Combine

struct SplashView: View {
    private let container: DIContainer
    @State private var showHomeView: Bool = false
    @State private var showAuthenticationView: Bool = false

    /// setup routings' bindings
    @State private var routingState: Routing = .init()
    private var routingBinding: Binding<Routing> {
        $routingState.dispatched(to: container.appState, \.routing.splash)
    }
    
    init(container: DIContainer) {
        self.container = container
    }
    
    @ViewBuilder
    var body: some View {
        NavigationView {
            ZStack {
                Color.background
                    .edgesIgnoringSafeArea(.all)
                VStack {
                    Image("logo")
                        .resizable()
                        .frame(width: 153, height: 60, alignment: .center)
                }
                
                if container.interactors.splashInteractor.isLogin {
                    NavigationLink(
                        destination: HomeView(),
                        isActive: $showHomeView) { EmptyView() }
                } else {
                    NavigationLink(
                        destination: AuthenticationView(),
                        isActive: $showAuthenticationView) { EmptyView() }
                }
            }
            .navigationBarHidden(true)
        }
        .onAppear {
            container.appState[\.routing] = AppState.ViewRouting()
            
            if container.interactors.splashInteractor.isLogin {
                showHomeView = true
            } else {
                showAuthenticationView = true
            }
        }
        .inject(container) // inject the dependency container to the view heirarchy.
//        .onReceive(routingUpdate) { self.routingState = $0 }
    }
    
    /// goint to new page with some delay
    /// - Parameter delay: delay as time interval
    private func handleNavigation(after delay: TimeInterval, completion: @escaping () -> Void) {
        DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: completion)
    }
}

// MARK: - Routing

extension SplashView {
    struct Routing: Equatable {
        var shouldNavigateToHome: Bool = false
        var shouldNavigateToAuthentication: Bool = false
        
        mutating func clear() {
            shouldNavigateToHome = false
            shouldNavigateToAuthentication = false
        }
    }
}

// MARK: - State Update

extension SplashView {
    var routingUpdate: AnyPublisher<Routing, Never> {
        container.appState.updates(for: \.routing.splash)
    }
}

// MARK: - Preview

struct SplashView_Previews: PreviewProvider {
    static var previews: some View {
        SplashView(container: .preview)
    }
}

**Comment by MohsenKhosravinia** [comment]
It doesn't format properly. do you want me to upload the project and give you a link?

**Comment by MohsenKhosravinia** [comment]
@nalexn Would you please take a look at this project? 
[https://gitlab.com/MohsenKhosravinia/cleanarchvaiyo](url)

**Comment by nalexn** [comment]
Ok, after a quick glance I think you should remove `NavigationLink` here and leave just the `Button`:

```swift
NavigationLink(destination: AuthenticationView(), isActive: routingBinding.shouldNavigateToAuthetication) {
    Button {
        logout()
    } label: {
        Image(systemName: "power")
            //...
    }
}
```
then, I'd removed the `var shouldNavigateToAuthetication: Bool = false` in the `HomeView.Routing`. In your `logout`, instead of

```swift
injected.appState[\.routing.home.shouldNavigateToAuthetication] = true
```
you should toggle the `container.interactors.splashInteractor.isLogin`, since I can see it toggles between `AuthenticationView` and `HomeView`:

```swift
if container.interactors.splashInteractor.isLogin {
    NavigationLink(
        destination: HomeView(),
        isActive: $showHomeView) { EmptyView() }
} else {
    NavigationLink(
        destination: AuthenticationView(),
        isActive: $showAuthenticationView) { EmptyView() }
}
```

**Comment by MohsenKhosravinia** [comment]
Thank you for the effort but I want to go forward (after log out I want to instantiate new authentication view). I did follow your steps but the log out button does nothing without navigation link. When we instantiate a view twice (based on a UX situation) we don't get the proper result because the app state holds the routing last states and the automatic navigation happens afterward. Do you have any suggestion on that? I was trying to reset the AppState.Routing struct on the .onAppear or .onDisappear but the result was messy and not satisfying.

**Comment by nalexn** [comment]
Ok, then if you actually need to show another AuthenticationView and not pop back to the original, the second one has to rely on separate routing parameters. Introduce a secondary set of routing params for AuthenticationView, and then control which set to use by providing an enum or a bool value as init parameter for the AuthenticationView
