### ISSUE TITLE
safearea is not correct

### ISSUE THREAD

**Issue by oleg-moseyko** [nalexn/clean-architecture-swiftui#82]
<img width="419" alt="Снимок экрана 2022-11-11 в 00 10 32" src="https://user-images.githubusercontent.com/25344716/201225315-017cc55e-3f98-4d53-9250-911d8c6a5229.png">

**Comment by gap1994** [comment]
use ignoresSafeArea

**Comment by torburg** [comment]
@nalexn fixed this issue here: https://github.com/nalexn/clean-architecture-swiftui/pull/86
