### ISSUE TITLE
App doesn't build

### ISSUE THREAD

**Issue by GJNilsen** [nalexn/clean-architecture-swiftui#9]
/UnitTests/Mocks/MockedInteractors.swift:38:14: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'loadCountryDetails(_:)' (identifier_name)

/UnitTests/Mocks/MockedInteractors.swift:63:14: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'loadImage(_:)' (identifier_name)

/UnitTests/Mocks/MockedWebRepositories.swift:25:14: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'loadCountryDetails(_:)' (identifier_name)

/UnitTests/Mocks/MockedWebRepositories.swift:48:14: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'loadImage(_:)' (identifier_name)

/CountriesSwiftUI/Repositories/CountriesWebRepository.swift:49:14: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'countryDetails(_:)' (identifier_name)

/CountriesSwiftUI/Utilities/APICall.swift:20:10: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'httpCode(_:)' (identifier_name)

/CountriesSwiftUI/System/SystemEventsHandler.swift:80:14: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'showCountryFlag(alpha3Code:)' (identifier_name)

/CountriesSwiftUI/Utilities/Loadable.swift:14:10: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'isLoading(last:)' (identifier_name)

/CountriesSwiftUI/Utilities/Loadable.swift:15:10: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'loaded(_:)' (identifier_name)

/CountriesSwiftUI/Utilities/Loadable.swift:16:10: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'failed(_:)' (identifier_name)

**Comment by nalexn** [comment]
Run this in Terminal:

`brew uninstall --force swiftlint && brew install swiftlint`

**Comment by nalexn** [comment]
@GJNilsen , alternatively, you can remove the Swiftlint check from the Build Phases. Closing this issue

<img width="755" alt="Screenshot 2020-01-23 at 13 13 43" src="https://user-images.githubusercontent.com/1594746/72963796-608d5600-3de2-11ea-81e1-530d9a8f7516.png">

**Comment by GJNilsen** [comment]
Thanks. Btw Swiftlint should probably be listed as a requirement in the read me.

**Comment by nalexn** [comment]
It's not a requirement. Shell command checks if swiftlint is installed and skips this step otherwise:

```
if command -v swiftlint > /dev/null; then
  swiftlint lint --config "${SRCROOT}/.swiftlint.yml"
fi
```

**Comment by nalexn** [comment]
In your case, you probably had a quite old swiftlint version that didn't support some commands from the config file
