### ISSUE TITLE
DIContainer conforming EnvironmentKey - can't find its usage

### ISSUE THREAD

**Issue by vanjang** [nalexn/clean-architecture-swiftui#93]
Just wonder why `DIContainer` conforms `EnvironmentKey` in the project as I am not able to find its usage with `EnviromentValues` across the project. The projects builds fine with commenting `EnvironmentKey`. Could anyone explain? I don't have enough knowledge on `EnvironmentKey` therefore I may miss something on how to use it.

**Comment by Eirias** [comment]
Check the [RootViewModifier](https://github.com/nalexn/clean-architecture-swiftui/blob/master/CountriesSwiftUI/UI/RootViewModifier.swift) on the master branch, it uses:
`@Environment(\.injected) private var injected: DIContainer`

**Comment by vanjang** [comment]
Ah got it! I am on mvvm branch and it doesn't have the code you advised above. Thanks and problem solved!
